### ISSUE TITLE
Commas inside quoted fields breaks column reading

### ISSUE THREAD

**Issue by md0u80c9** [jimhester/vroom#65] opened 2019-03-23 12:32 UTC
I've had trouble importing a text file this morning; when I've looked at it I think this is an issue with delimiter reading in combination with quoted fields.

For reasons not known to me, I'm given CSV files where all field values are quoted "". In one field there are two comma delimiters within the quoted text, which is being interpreted as being three column values. Subsequently this then throws the rest of the files out.

Possibly complicating this is the use of col_guess() for undefined columns (including the column in question) as these columns are custom fields.

I've tried to build a reproducible example - Dogs.txt doesn't quite exhibit the problem I wanted, but exhibits enough problems that it probably encapsulates the issue.

If we load dogs.txt with:

```
dog_cols <- readr::cols(Animal = readr::col_character(), Legs = readr::col_integer(), Comments = readr::col_character(), Owners = readr::col_integer(), HasTeeth = readr::col_logical())
test <- vroom::vroom("../Team Data/Dogs.txt", col_types = dog_cols)

```

> Error in vroom_(file, delim = delim, col_names = col_names, col_types = col_types,  :                                           
>   Not compatible with STRSXP: [type=NULL].
> 

If we specify the delimiter:

`test <- vroom::vroom("../Team Data/Dogs.txt", col_types = dog_cols, delim = ",")
`
We also fail.

If we test the same code in readr:

`test <- readr::read_csv("../Team Data/Dogs.txt", col_types = dog_cols)
`

> Warning: 1 parsing failure.
> row col  expected    actual                    file
>   2  -- 6 columns 5 columns '../Team Data/Dogs.txt'
> 
> Warning message:
> Missing column names filled in: 'X6' [6] 
> 

Then the code will read but will insert an extra column at the end (so this may be a readr issue rather than a vroom one, albeit the error codes are different.

[Dogs.txt](https://github.com/jimhester/vroom/files/2999330/Dogs.txt)

**Comment by jimhester** [comment] 2019-03-25 14:21
There are at least three strange things in this file. 

1. The delimiter embedded in the quoted field, which is not really strange, but the guessing function did not handle this case (fixed by https://github.com/jimhester/vroom/commit/93ea8d4a1833070546db5dcb764f36b703db9cba)
2. The first two lines have a trailing `,`, which is also unnamed. The vroom parser actually handled this, but because it was un-named the tibble constructor threw (correctly) an error. This was fixed by exposing the `.name_repair` argument to tibble, and setting the default to "unique" (https://github.com/jimhester/vroom/commit/d8f10c998d2ddd2d0cbb2080f68fc15142515515)
3. The third line is incomplete, it does _not_ have a trailing column. I am not sure what the best behavior for this would be, but currently vroom does not ensure consistency of column lengths, (#29).

So for now I think I will close this, thank you for the small reproducible example!

**Closed by jimhester** 2019-03-25 14:21 UTC

**Comment by md0u80c9** [comment] 2019-03-25 17:25
Oops a triple reprex! The trailing commas were an accident from hand-crafting the CSV for testing but glad that exposed a secondary issue 🤷‍♂️. The first issue is the one which I think will have affected my source file - will test that tonight and let you know!

**Comment by md0u80c9** [comment] 2019-03-26 09:36
Right - tested again with my real files.

I think (d8f10c9) has caused a regression.

The original issue I found (which I used as the basis for the reprex) were when I exported 'custom data fields' from the dataset (where the users can edit stuff - including blank / repeated column names!) When running the CSV data export you can include or exclude those from.

The previous version of vroom worked on the dataset if you only exported the 'standard' dataset, and it was only when exporting the additional data within the 'custom' dataset which caused an issue.

On the latest version (with two CSV files using the 'standard' dataset in the 'Team Data' directory), I now see the following:

```
> files <- fs::dir_ls(path = "../Team Data", glob = "*csv")
> df1 <- ssnapinterface::read_audit_csv(files)
Error in tibble::as_tibble(out, .name_repair = .name_repair) :                                                                                                                    
  R_Reprotect: only -4 protected items, can't reprotect index -6
In addition: Warning message:
 Error in tibble::as_tibble(out, .name_repair = .name_repair) : 
  R_Reprotect: only -4 protected items, can't reprotect index -6 
3.
tibble::as_tibble(out, .name_repair = .name_repair) 
2.
vroom::vroom(filename, col_types = col_types, delim = ",") at read_csv.R#52
1.
ssnapinterface::read_audit_csv(files) 

I also find that running it R becomes unstable (which I've not seen previously) - I've had it crash when I subsequently try to rm(df1); and I can reliably crash R by repeating those commands a couple of times - sometimes forcing R into an infinite loop that requires RStudio to be Force Quit.

```

**Comment by md0u80c9** [comment] 2019-03-26 09:54
Just tested with a single file. Interestingly the error is slightly different - but the end results are the same (error message and R trying to blow up with a fatal error):

```
> df1 <- ssnapinterface::read_audit_csv("../Team Data/295.csv")
Error in tibble::as_tibble(out, .name_repair = .name_repair) :                                                                                                                    
  R_Reprotect: only 1 protected item, can't reprotect index -1
In addition: Warning message:
 Error in tibble::as_tibble(out, .name_repair = .name_repair) : 
  R_Reprotect: only 1 protected item, can't reprotect index -1 
```

**Comment by md0u80c9** [comment] 2019-04-03 16:56
Hi,

Just checking you picked up the above re the probably regression. Did you want me to open that up as a separate issue?

**Comment by jimhester** [comment] 2019-04-08 19:27
Please open a new issue preferably with some data I can run locally.

Also the error you are showing is very strange, vroom does not use `R_Reprotect()` at all, and the error is happening when converting the list to a tibble, so possibly something other than vroom is the cause.

**Comment by jimhester** [comment] 2019-04-08 21:14
Update, I was able to reproduce the stack imbalance errors and it is a bug in vroom. I now know the issue and am working on a fix.

**Comment by md0u80c9** [comment] 2019-04-09 08:06
Awesome - great stuff. I'll test it again this evening.
